# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop
- feature/*
- master

pool:
  name: batch26

variables:
  buildConfiguration: 'Release'
  dotNetFramework: 'net6.0'
  dotNetVersion: '6.0.300'
  targetRuntime: 'linux-x64'

stages:
- stage: 'Build'
  jobs:
  - job: 'Build'
    steps:
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'

    
    task: DotNetCoreCLI@2
      displayName: Publish projects
      inputs:
      command: 'publish'
      publishWebProjects: true
      arguments: 'dotnet build --configuration $(buildConfiguration)'
      zipAfterPublish: true